version: '3'

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_USER:      adelantado
      POSTGRES_PASSWORD:  adelantado
      POSTGRES_DB:        adelantado
    ports:
      - 25432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations/1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./migrations/2-data.sql:/docker-entrypoint-initdb.d/2-data.sql

volumes:
  postgres-data: