{
 "title": "Adelantado",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Download count",
   "type": "graph",
   "description": "Download pages count",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(adelantado_download_page_count[$interval])"
    }
   ]
  },
  {
   "title": "Failed count",
   "type": "graph",
   "description": "Failed procees pages count",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(adelantado_failed_page_count[$interval])"
    }
   ]
  },
  {
   "title": "Parsing duration",
   "type": "graph",
   "description": "Page parsing duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(adelantado_parse_page_duration[$interval])"
    }
   ]
  },
  {
   "title": "Download duration",
   "type": "graph",
   "description": "Download page spend time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(adelantado_download_page_duration[$interval])"
    }
   ]
  },
  {
   "title": "Total duration",
   "type": "graph",
   "description": "Download + parse page durations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(adelantado_processing_page_total_duration[$interval])"
    }
   ]
  },
  {
   "title": "Reg link duration",
   "type": "graph",
   "description": "How many time spend to register new link",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(adelantado_register_link_duration[$interval])"
    }
   ]
  },
  {
   "title": "Reg link count",
   "type": "graph",
   "description": "How many links were registered",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(adelantado_register_link_count[$interval])"
    }
   ]
  }
 ]
}